"""Create tables

Revision ID: a5cda9debe7f
Revises: 
Create Date: 2024-07-27 22:38:07.380103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cda9debe7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('continentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('continente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['continente_id'], ['continentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_musicales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('anio_formacion', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupos_musicales')
    op.drop_table('generos')
    op.drop_table('continentes')
    # ### end Alembic commands ###
